import { z } from 'zod';

const envInput = {
  ...process.env,
  PORT: process.env.SUBSCRIPTION_PORT ?? process.env.PORT,
  MONGODB_URI: process.env.MONGODB_URI ?? process.env.MONGO_URI,
  HRM_ACCESS_TOKEN_SECRET: process.env.HRM_ACCESS_TOKEN_SECRET ?? process.env.ACCESS_TOKEN_SECRET ?? '',
};

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'staging', 'production']).default('development'),
  PORT: z.coerce.number().int().positive().default(3000),
  MONGODB_URI: z.string().min(1),
  REDIS_URL: z.string().min(1),
  JWT_SECRET: z.string().min(16),
  ADMIN_JWT_SECRET: z.string().min(16),
  HRM_ACCESS_TOKEN_SECRET: z.string().optional().default(''),
  INTERNAL_API_KEY: z.string().min(8),
  API_KEY_PEPPER: z.string().min(8),
  PASSWORD_PEPPER: z.string().min(8),
  AUTH_TOKEN_PEPPER: z.string().min(8),
  Razorpay_KEY_ID: z.string().optional().default(''),
  Razorpay_KEY_SECRET: z.string().optional().default(''),
  RAZORPAY_WEBHOOK_SECRET: z.string().optional().default(''),
  RESEND_API_KEY: z.string().optional().default(''),
  RESEND_FROM_EMAIL: z.string().optional().default(''),
  APP_BASE_URL: z.string().optional().default(''),
  S3_BUCKET: z.string().optional().default(''),
  S3_REGION: z.string().optional().default('ap-south-1'),
  S3_ENDPOINT: z.string().optional().default(''),
  S3_FORCE_PATH_STYLE: z.string().optional().default('false'),
  S3_PUBLIC_BASE_URL: z.string().optional().default(''),
  AWS_ACCESS_KEY_ID: z.string().optional().default(''),
  AWS_SECRET_ACCESS_KEY: z.string().optional().default(''),
  AWS_SESSION_TOKEN: z.string().optional().default(''),
  SUPER_ADMIN_EMAIL: z.string().optional().default(''),
  SUPER_ADMIN_PASSWORD: z.string().optional().default(''),
  SUPER_ADMIN_NAME: z.string().optional().default(''),
  SENTRY_DSN: z.string().optional().default(''),
  POSTHOG_API_KEY: z.string().optional().default(''),
  POSTHOG_HOST: z.string().url().optional().default('https://app.posthog.com'),
  OUTBOX_DELIVERY_URL: z.string().optional().default(''),
  OUTBOX_DELIVERY_SECRET: z.string().optional().default(''),
  OUTBOX_MAX_ATTEMPTS: z.coerce.number().int().positive().optional().default(5),
  OUTBOX_RETRY_BASE_DELAY_MS: z.coerce.number().int().positive().optional().default(1000),
  OUTBOX_REQUEST_TIMEOUT_MS: z.coerce.number().int().positive().optional().default(5000),
  SESSION_MAX_AGE_HOURS: z.coerce.number().int().positive().optional().default(8),
});

export const env = envSchema.parse(envInput);
