import type { PlanDefinition } from './plan.types';

const baseFeatures = {
  employeeManagement: true,
  attendance: true,
  leaveManagement: true,
  basicReports: true,
  payroll: false,
  taskManagement: false,
  employeeSelfService: false,
  announcements: false,
  shiftManagement: false,
  advancedReports: false,
  auditLogs: false,
  employeeDocuments: false,
  customFields: false,
  dataExport: false,
  approvalWorkflows: false,
  recruitment: false,
  performanceReviews: false,
  assetManagement: false,
  apiAccess: false,
  workflowAutomation: false,
  customBranding: false,
  sso: false,
  whiteLabel: false,
  leadPortal: false,
  prioritySupport: false,
  customIntegrations: false,
};

export const defaultPlans: PlanDefinition[] = [
  {
    code: 'free',
    name: 'Free',
    version: 1,
    hidden: false,
    purchasable: true,
    systemManaged: false,
    employeeLimit: 5,
    billingInterval: 'month',
    priceMonthly: 0,
    priceYearly: 0,
    currency: 'INR',
    features: { ...baseFeatures },
  },
  {
    code: 'starter',
    name: 'Starter',
    version: 1,
    hidden: false,
    purchasable: true,
    systemManaged: false,
    employeeLimit: 25,
    billingInterval: 'month',
    priceMonthly: 999,
    priceYearly: 9990,
    currency: 'INR',
    features: { ...baseFeatures },
  },
  {
    code: 'growth',
    name: 'Growth',
    version: 1,
    hidden: false,
    purchasable: true,
    systemManaged: false,
    employeeLimit: 100,
    billingInterval: 'month',
    priceMonthly: 2499,
    priceYearly: 24990,
    currency: 'INR',
    features: { ...baseFeatures, payroll: true, taskManagement: true, employeeSelfService: true, announcements: true, shiftManagement: true, advancedReports: true, employeeDocuments: true, customFields: true, dataExport: true, approvalWorkflows: true },
  },
  {
    code: 'professional',
    name: 'Professional',
    version: 1,
    hidden: false,
    purchasable: true,
    systemManaged: false,
    employeeLimit: 500,
    billingInterval: 'month',
    priceMonthly: 4999,
    priceYearly: 49990,
    currency: 'INR',
    features: { ...baseFeatures, payroll: true, taskManagement: true, employeeSelfService: true, announcements: true, shiftManagement: true, advancedReports: true, auditLogs: true, employeeDocuments: true, customFields: true, dataExport: true, approvalWorkflows: true, recruitment: true, performanceReviews: true, assetManagement: true, apiAccess: true, workflowAutomation: true },
  },
  {
    code: 'enterprise',
    name: 'Enterprise',
    version: 1,
    hidden: false,
    purchasable: true,
    systemManaged: false,
    employeeLimit: null,
    billingInterval: 'month',
    priceMonthly: 0,
    priceYearly: 0,
    currency: 'INR',
    features: { ...baseFeatures, payroll: true, taskManagement: true, employeeSelfService: true, announcements: true, shiftManagement: true, advancedReports: true, auditLogs: true, employeeDocuments: true, customFields: true, dataExport: true, approvalWorkflows: true, recruitment: true, performanceReviews: true, assetManagement: true, apiAccess: true, workflowAutomation: true, customBranding: true, sso: true, whiteLabel: true, leadPortal: true, prioritySupport: true, customIntegrations: true },
  },
  {
    code: 'legacy',
    name: 'Legacy',
    version: 1,
    hidden: true,
    purchasable: false,
    systemManaged: true,
    employeeLimit: null,
    billingInterval: 'month',
    priceMonthly: 0,
    priceYearly: 0,
    currency: 'INR',
    features: { ...baseFeatures, payroll: true, taskManagement: true, employeeSelfService: true, announcements: true, shiftManagement: true, advancedReports: true, auditLogs: true, employeeDocuments: true, customFields: true, dataExport: true, approvalWorkflows: true, recruitment: true, performanceReviews: true, assetManagement: true, apiAccess: true, workflowAutomation: true, customBranding: true, sso: true, whiteLabel: true, leadPortal: true, prioritySupport: true, customIntegrations: true },
  },
];
